# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://manik-500.github.io/fastgan/"

git_url = "https://github.com/manik-500/fastgan/tree/{branch}/"

def custom_doc_links(name): return None
